### PR TITLE
Modify quazip for use in Mumble

### PR DESCRIPTION
**Pull request by Krzmbrzl**
This is required for https://github.com/mumble-voip/mumble/pull/3743

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
@davidebeatrici Don't know, if you get notifications for this repo, so I'm gonna ping you directly :)

**Comment by Krzmbrzl** [comment]
Ah actually I don't think we need these changes after all. I found out how Mumble deals with this kind of problem and I have to say, that I think it's smarter that way.
Thus it seems as if this PR won't be necessary after all :man_shrugging:

**Comment by davidebeatrici** [comment]
Also, consider that once Mumble's CMake project is ready we can simply add `quazip` as submodule.

**Comment by Krzmbrzl** [comment]
I got it working now in any event. No need for these changes :)

**Pull request closed without merging**
